config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
  get 'tasks/:id', to: 'tasks#show', as: :task


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/Tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to "/tasks"
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with model: @task, url: "/tasks/#{@task.id}", method: :patch do |f| %>
  <div><%= f.label :title %><br><%= f.text_field :title %></div>
  <div><%= f.label :details %><br><%= f.text_area :details %></div>
  <div><%= f.label :completed %><br><%= f.check_box :completed %></div>
  <%= f.submit "Update Task" %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_path(task.id) %>
      <%= task.completed ? "✅ Completed" : "❌ Not completed" %>
      <%= link_to "Edit", edit_task_path(task.id) %>
      <%= link_to "Delete", task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<%= link_to "New Task", "/tasks/new" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task do |f| %>
  <div><%= f.label :title %><br><%= f.text_field :title %></div>
  <div><%= f.label :details %><br><%= f.text_area :details %></div>
  <%= f.submit "Create Task" %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p>Status: <%= @task.completed ? "✅ Completed" : "❌ Not completed" %></p>
<%= link_to "Back", tasks_path %>